[project]
site_name = "karotte"
site_description = "Build robust RL environments to train aligned AI."
site_url = "https://karotte.dev/"
repo_url = "https://github.com/preferencemodel/karotte"
repo_name = "preferencemodel/karotte"
edit_uri = "edit/main/docs/"
copyright = "MIT licensed"
nav = [
  { "Home" = "index.md" },
]

[project.theme]
language = "en"
features = [
  "content.action.edit",
  "content.code.copy",
  "content.tabs.link",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc.permalink = true
pymdownx.details = {}
pymdownx.highlight.anchor_linenums = true
pymdownx.highlight.pygments_lang_class = true
pymdownx.inlinehilite = {}
pymdownx.superfences.custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
pymdownx.tabbed.alternate_style = true
pymdownx.tasklist.custom_checkbox = true
